swagger: "2.0"
servers:
  - url: http://127.0.0.1:8080/v1
    description: development server
info:
  version: "1.0.0"
  title: ZeldaBooK api definition
  description: The API for the ZeldaBooK project
  contact:
    name: jaguarliu(刘佳鹏)
    email: jaguarliu@tencent.com
    url: https://github.com/colin404
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT